### ISSUE TITLE
3-18 章的 h_aware 是不是跑不起来啊？

### ISSUE THREAD

**Issue by flyingHuaJi** [LinkedBear/spring-framework-learning-code#10]
3-18 章的 h_aware 是不是跑不起来啊？

虽然配置了 ComponentScan 的扫描路径， 但是 AwaredTestBean 上面并没有加 @Component，导致在 ctx.getBean(AwaredTestBean.class) 的时候会抛出：NoSuchBeanDefinitionException

**Comment by LinkedBear** [comment]
是的我同步两个仓库代码的时候漏掉了@Component注解，已经修复好代码啦，感谢小伙伴勘误~
